substitutions:
  device_name: Solax
  device_description: Solax x3 data reader
  version: "v1"

esphome:
  name: ${device_name}
  comment: "${device_description}" 
  name_add_mac_suffix: false
  
  project:
    name: Solax.datareader
    version: ${version}
  
esp8266:
  board: esp01_1m
  restore_from_flash: true

status_led:
  pin:
    number: 2
    inverted: true

dashboard_import:
  package_import_url: github://supershadow/SolaxX3/solax.yaml

wifi:
#  ssid: !secret ssid
#  password: !secret password
  
  ap:
    ssid: ${device_name}

    
web_server:
  port: 80
